/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as masterChefSol from "./MasterChef.sol";
export type { masterChefSol };
export type { IMasterChef } from "./IMasterChef";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { MyTokenMarket } from "./MyTokenMarket";
export type { SushiToken } from "./SushiToken";
export type { Terry20 } from "./Terry20";
