/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMasterChef,
  IMasterChefInterface,
} from "../../contracts/IMasterChef";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMasterChef__factory {
  static readonly abi = _abi;
  static createInterface(): IMasterChefInterface {
    return new utils.Interface(_abi) as IMasterChefInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMasterChef {
    return new Contract(address, _abi, signerOrProvider) as IMasterChef;
  }
}
